//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub21eng
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Meeting.
    /// </summary>
    // *** Start programmer edit section *** (Meeting CustomAttributes)

    // *** End programmer edit section *** (Meeting CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MeetingE", new string[] {
            "Date as \'Date\'"})]
    [AssociatedDetailViewAttribute("MeetingE", "Presentation", "PresentationE", true, "", "Presentation", true, new string[] {
            ""})]
    [View("MeetingL", new string[] {
            "Date as \'Date\'"})]
    public class Meeting : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDate;
        
        private IIS.BookClub21eng.DetailArrayOfPresentation fPresentation;
        
        // *** Start programmer edit section *** (Meeting CustomMembers)

        // *** End programmer edit section *** (Meeting CustomMembers)

        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Meeting.Date CustomAttributes)

        // *** End programmer edit section *** (Meeting.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Meeting.Date Get start)

                // *** End programmer edit section *** (Meeting.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Meeting.Date Get end)

                // *** End programmer edit section *** (Meeting.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Meeting.Date Set start)

                // *** End programmer edit section *** (Meeting.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Meeting.Date Set end)

                // *** End programmer edit section *** (Meeting.Date Set end)
            }
        }
        
        /// <summary>
        /// Meeting.
        /// </summary>
        // *** Start programmer edit section *** (Meeting.Presentation CustomAttributes)

        // *** End programmer edit section *** (Meeting.Presentation CustomAttributes)
        public virtual IIS.BookClub21eng.DetailArrayOfPresentation Presentation
        {
            get
            {
                // *** Start programmer edit section *** (Meeting.Presentation Get start)

                // *** End programmer edit section *** (Meeting.Presentation Get start)
                if ((this.fPresentation == null))
                {
                    this.fPresentation = new IIS.BookClub21eng.DetailArrayOfPresentation(this);
                }
                IIS.BookClub21eng.DetailArrayOfPresentation result = this.fPresentation;
                // *** Start programmer edit section *** (Meeting.Presentation Get end)

                // *** End programmer edit section *** (Meeting.Presentation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Meeting.Presentation Set start)

                // *** End programmer edit section *** (Meeting.Presentation Set start)
                this.fPresentation = value;
                // *** Start programmer edit section *** (Meeting.Presentation Set end)

                // *** End programmer edit section *** (Meeting.Presentation Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MeetingE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingE", typeof(IIS.BookClub21eng.Meeting));
                }
            }
            
            /// <summary>
            /// "MeetingL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MeetingL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MeetingL", typeof(IIS.BookClub21eng.Meeting));
                }
            }
        }
    }
}
