//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BookClub21eng
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Presentation.
    /// </summary>
    // *** Start programmer edit section *** (Presentation CustomAttributes)

    // *** End programmer edit section *** (Presentation CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PresentationE", new string[] {
            "Date as \'Date\'",
            "Rating as \'Rating\'",
            "URLPresentation as \'U r l presentation\'",
            "URLVideo as \'U r l video\'",
            "Review as \'Review\'",
            "Speaker as \'Speaker\'",
            "Speaker.FirstName as \'First name\'",
            "Book as \'Book\'",
            "Book.Title as \'Title\'"}, Hidden=new string[] {
            "Speaker.FirstName",
            "Book.Title"})]
    [MasterViewDefineAttribute("PresentationE", "Speaker", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "FirstName")]
    [MasterViewDefineAttribute("PresentationE", "Book", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Title")]
    public class Presentation : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fDate;
        
        private int fRating;
        
        private string fURLPresentation;
        
        private string fURLVideo;
        
        private string fReview;
        
        private IIS.BookClub21eng.Speaker fSpeaker;
        
        private IIS.BookClub21eng.Book fBook;
        
        private IIS.BookClub21eng.Meeting fMeeting;
        
        // *** Start programmer edit section *** (Presentation CustomMembers)

        // *** End programmer edit section *** (Presentation CustomMembers)

        
        /// <summary>
        /// Date.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Date CustomAttributes)

        // *** End programmer edit section *** (Presentation.Date CustomAttributes)
        public virtual System.DateTime Date
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Date Get start)

                // *** End programmer edit section *** (Presentation.Date Get start)
                System.DateTime result = this.fDate;
                // *** Start programmer edit section *** (Presentation.Date Get end)

                // *** End programmer edit section *** (Presentation.Date Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Date Set start)

                // *** End programmer edit section *** (Presentation.Date Set start)
                this.fDate = value;
                // *** Start programmer edit section *** (Presentation.Date Set end)

                // *** End programmer edit section *** (Presentation.Date Set end)
            }
        }
        
        /// <summary>
        /// Rating.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Rating CustomAttributes)

        // *** End programmer edit section *** (Presentation.Rating CustomAttributes)
        public virtual int Rating
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Rating Get start)

                // *** End programmer edit section *** (Presentation.Rating Get start)
                int result = this.fRating;
                // *** Start programmer edit section *** (Presentation.Rating Get end)

                // *** End programmer edit section *** (Presentation.Rating Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Rating Set start)

                // *** End programmer edit section *** (Presentation.Rating Set start)
                this.fRating = value;
                // *** Start programmer edit section *** (Presentation.Rating Set end)

                // *** End programmer edit section *** (Presentation.Rating Set end)
            }
        }
        
        /// <summary>
        /// Review.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Review CustomAttributes)

        // *** End programmer edit section *** (Presentation.Review CustomAttributes)
        [StrLen(255)]
        public virtual string Review
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Review Get start)

                // *** End programmer edit section *** (Presentation.Review Get start)
                string result = this.fReview;
                // *** Start programmer edit section *** (Presentation.Review Get end)

                // *** End programmer edit section *** (Presentation.Review Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Review Set start)

                // *** End programmer edit section *** (Presentation.Review Set start)
                this.fReview = value;
                // *** Start programmer edit section *** (Presentation.Review Set end)

                // *** End programmer edit section *** (Presentation.Review Set end)
            }
        }
        
        /// <summary>
        /// URLPresentation.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.URLPresentation CustomAttributes)

        // *** End programmer edit section *** (Presentation.URLPresentation CustomAttributes)
        [StrLen(255)]
        public virtual string URLPresentation
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.URLPresentation Get start)

                // *** End programmer edit section *** (Presentation.URLPresentation Get start)
                string result = this.fURLPresentation;
                // *** Start programmer edit section *** (Presentation.URLPresentation Get end)

                // *** End programmer edit section *** (Presentation.URLPresentation Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.URLPresentation Set start)

                // *** End programmer edit section *** (Presentation.URLPresentation Set start)
                this.fURLPresentation = value;
                // *** Start programmer edit section *** (Presentation.URLPresentation Set end)

                // *** End programmer edit section *** (Presentation.URLPresentation Set end)
            }
        }
        
        /// <summary>
        /// URLVideo.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.URLVideo CustomAttributes)

        // *** End programmer edit section *** (Presentation.URLVideo CustomAttributes)
        [StrLen(255)]
        public virtual string URLVideo
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.URLVideo Get start)

                // *** End programmer edit section *** (Presentation.URLVideo Get start)
                string result = this.fURLVideo;
                // *** Start programmer edit section *** (Presentation.URLVideo Get end)

                // *** End programmer edit section *** (Presentation.URLVideo Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.URLVideo Set start)

                // *** End programmer edit section *** (Presentation.URLVideo Set start)
                this.fURLVideo = value;
                // *** Start programmer edit section *** (Presentation.URLVideo Set end)

                // *** End programmer edit section *** (Presentation.URLVideo Set end)
            }
        }
        
        /// <summary>
        /// Presentation.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Book CustomAttributes)

        // *** End programmer edit section *** (Presentation.Book CustomAttributes)
        [PropertyStorage(new string[] {
                "Book"})]
        [NotNull()]
        public virtual IIS.BookClub21eng.Book Book
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Book Get start)

                // *** End programmer edit section *** (Presentation.Book Get start)
                IIS.BookClub21eng.Book result = this.fBook;
                // *** Start programmer edit section *** (Presentation.Book Get end)

                // *** End programmer edit section *** (Presentation.Book Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Book Set start)

                // *** End programmer edit section *** (Presentation.Book Set start)
                this.fBook = value;
                // *** Start programmer edit section *** (Presentation.Book Set end)

                // *** End programmer edit section *** (Presentation.Book Set end)
            }
        }
        
        /// <summary>
        /// Presentation.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Speaker CustomAttributes)

        // *** End programmer edit section *** (Presentation.Speaker CustomAttributes)
        [PropertyStorage(new string[] {
                "Speaker"})]
        [NotNull()]
        public virtual IIS.BookClub21eng.Speaker Speaker
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Speaker Get start)

                // *** End programmer edit section *** (Presentation.Speaker Get start)
                IIS.BookClub21eng.Speaker result = this.fSpeaker;
                // *** Start programmer edit section *** (Presentation.Speaker Get end)

                // *** End programmer edit section *** (Presentation.Speaker Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Speaker Set start)

                // *** End programmer edit section *** (Presentation.Speaker Set start)
                this.fSpeaker = value;
                // *** Start programmer edit section *** (Presentation.Speaker Set end)

                // *** End programmer edit section *** (Presentation.Speaker Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.BookClub21eng.Meeting.
        /// </summary>
        // *** Start programmer edit section *** (Presentation.Meeting CustomAttributes)

        // *** End programmer edit section *** (Presentation.Meeting CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Meeting"})]
        public virtual IIS.BookClub21eng.Meeting Meeting
        {
            get
            {
                // *** Start programmer edit section *** (Presentation.Meeting Get start)

                // *** End programmer edit section *** (Presentation.Meeting Get start)
                IIS.BookClub21eng.Meeting result = this.fMeeting;
                // *** Start programmer edit section *** (Presentation.Meeting Get end)

                // *** End programmer edit section *** (Presentation.Meeting Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Presentation.Meeting Set start)

                // *** End programmer edit section *** (Presentation.Meeting Set start)
                this.fMeeting = value;
                // *** Start programmer edit section *** (Presentation.Meeting Set end)

                // *** End programmer edit section *** (Presentation.Meeting Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PresentationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PresentationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PresentationE", typeof(IIS.BookClub21eng.Presentation));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Presentation.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfPresentation CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfPresentation CustomAttributes)
    public class DetailArrayOfPresentation : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.BookClub21eng.DetailArrayOfPresentation members)

        // *** End programmer edit section *** (IIS.BookClub21eng.DetailArrayOfPresentation members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Presentation by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Presentation.
        /// </summary>
        public DetailArrayOfPresentation(IIS.BookClub21eng.Meeting fMeeting) : 
                base(typeof(Presentation), ((ICSSoft.STORMNET.DataObject)(fMeeting)))
        {
        }
        
        public IIS.BookClub21eng.Presentation this[int index]
        {
            get
            {
                return ((IIS.BookClub21eng.Presentation)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.BookClub21eng.Presentation dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
